### ISSUE TITLE
Toast Errors should not be dismissed automatically

### ISSUE THREAD

**Issue by warm-coolguy** [Dataport/polar#19]
Toast errors disappear after some time. Errors should not disappear by themselves as decided here: https://github.com/Dataport/polar/pull/14#discussion_r1393242239

The client may not work correctly, and the error might contain relevant information to the user.

**TODO**

- [x] Remove timeouts for error toasts everywhere
- [x] Either ignore timeouts for errors (hard decision) or at least warn about timeouts on errors (softer)
- [x] Write an ADR regarding this decision
